version: "3"

services:
  reviewlah-admin:
    restart: always
    container_name: reviewlah-admin
    image: reviewlah-admin
    build:
      context:  ./reviewlah-admin
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - reviewlah-gateway
      - reviewlah-eureka
    links:
      - reviewlah-eureka
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS 'http://localhost:8086' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 6
    environment:
      EUREKASERVER_URI: "http://reviewlah-eureka:8761/eureka/"

  reviewlah-admin-vue:
    restart: always
    container_name: reviewlah-admin-vue
    image: reviewlah-admin-vue
    build:
      context: ./reviewlah-admin-vue
      dockerfile: Dockerfile
    ports:
      - "9527:9527"
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS 'http://localhost:9527' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 6
    links:
      - reviewlah-eureka

  reviewlah-comment:
    restart: always
    container_name:  reviewlah-comment
    image:  reviewlah-comment
    build:
      context: ./reviewlah-comment
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - reviewlah-gateway
      - reviewlah-eureka
    links:
      - reviewlah-eureka
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS 'http://localhost:8084' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 6
    environment:
      EUREKASERVER_URI: "http://reviewlah-eureka:8761/eureka/"


  reviewlah-customer:
    restart: always
    container_name: reviewlah-customer
    image: reviewlah-customer
    build:
      context: ./reviewlah-customer
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - reviewlah-gateway
      - reviewlah-eureka
    links:
      - reviewlah-eureka
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS 'http://localhost:8082' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 6
    environment:
      EUREKASERVER_URI: "http://reviewlah-eureka:8761/eureka/"


  reviewlah-merchant:
    restart: always
    container_name: reviewlah-merchant
    image: reviewlah-merchant
    build:
      context: ./reviewlah-merchant
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - reviewlah-gateway
      - reviewlah-eureka
    links:
      - reviewlah-eureka
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS 'http://localhost:8083' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 6
    environment:
      EUREKASERVER_URI: "http://reviewlah-eureka:8761/eureka/"


  reviewlah-message:
    restart: always
    container_name: reviewlah-message
    image: reviewlah-message
    build:
      context: ./reviewlah-message
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - reviewlah-gateway
      - reviewlah-eureka
    links:
      - reviewlah-eureka
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS 'http://localhost:8085' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 6
    environment:
      EUREKASERVER_URI: "http://reviewlah-eureka:8761/eureka/"

  reviewlah-eureka:
    restart: always
    container_name: reviewlah-eureka
    image: reviewlah-eureka
    build:
      context: ./reviewlah-eureka
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS 'http://localhost:8761' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 6
    ports:
      - "8761:8761"

  reviewlah-gateway:
    restart: always
    container_name: reviewlah-gateway
    image: reviewlah-gateway
    build:
      context: ./reviewlah-gateway
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - reviewlah-eureka
    links:
      - reviewlah-eureka
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS 'http://localhost:8081' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 6
    environment:
      EUREKASERVER_URI: "http://reviewlah-eureka:8761/eureka/"

