version: "3"

services:
  reviewlah-back:
    restart: always
    container_name: reviewlah-back
    image: reviewlah-back
    build:
      context:  ./reviewlah-back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "/data"

  reviewlah-vue:
    restart: always
    container_name: reviewlah-vue
    image: reviewlah-vue
    build:
      context: ./reviewlah-vue
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
