spring:
  application:
    name: comment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://review-db.cnglxiwein6d.ap-southeast-1.rds.amazonaws.com:3306/reviewlah-comment?characterEncoding=utf-8&useSSL=false
    username: admin
    password: ZHou*87721472
server:
  port: 8084
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
