spring:
  application:
    name: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?useSSL=false
    username:
    password:
server:
  port: 8086
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

